apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      type: NodePort
      containers:
      - name: myapp
        image: 634639955940.dkr.ecr.us-west-1.amazonaws.com/argocdtest:ver1.0
        ports:
        - containerPort: 8080

